spring.application.name=demo

logging.pattern.level=request_id:%X{request_id} %5p

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# 실행되는 SQL 출력
logging.level.org.hibernate.SQL=DEBUG

# SQL을 보기 좋게 정렬
spring.jpa.properties.hibernate.format_sql=true

# SQL의 ? 자리에 들어가는 실제 값 출력
logging.level.org.hibernate.orm.jdbc.bind=TRACE


# 로그가 저장될 로컬 장소
logging.file.name=logs/application.log

# 100MB가 넘어가면 하나의 압축파일을 만듬
logging.logback.rollingpolicy.max-file-size=100MB
# 만들어지는 압축파일 개수가 7개, 7개가 넘어가면 가장 오래된 기록부터 지운다.
logging.logback.rollingpolicy.max-history=7

# 최종적으로 담을수 있는 총 용량, 이 용량을 초과하게되면 오랜된 기록부터 지운다.
logging.logback.rollingpolicy.total-size-cap=3GB
