spring.application.name=demo

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/demo}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# 실행되는 SQL 출력
logging.level.org.hibernate.SQL=DEBUG

# SQL을 보기 좋게 정렬
spring.jpa.properties.hibernate.format_sql=true

# SQL의 ? 자리에 들어가는 실제 값 출력
logging.level.org.hibernate.orm.jdbc.bind=TRACE
